import React from 'react';
import { notFound } from 'next/navigation';
// Import utility functions from your markdown library
import { getMarkdownData, getAllPostSlugs, PostData } from '@/lib/markdown';

// Define the type for the URL parameters
interface PostPageProps {
  params: {
    slug: string;
  };
}

// --- Generic Component to Render Post Data ---
function PostContentRenderer({ post }: { post: PostData }) {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <h1 className="text-4xl font-bold font-display text-slate-900 dark:text-white mb-4">
        {post.title}
      </h1>
      <div className="text-sm text-slate-500 mb-8">
        Published on {post.date} | Category: {post.category}
      </div>
      
      {/* Renders the contentHtml generated by remark/remark-html */}
      <div 
        className="prose dark:prose-invert max-w-none" 
        dangerouslySetInnerHTML={{ __html: post.contentHtml }} 
      />
    </div>
  );
}
// ----------------------------------------------


/**
 * 1. generateStaticParams (REQUIRED for Next.js output: 'export')
 * This function uses your file system reader (getAllPostSlugs) to tell Next.js 
 * exactly which posts to pre-render based on the filenames in your _posts directory.
 */
export async function generateStaticParams() {
  // Use your utility function which reads the file system.
  return getAllPostSlugs(); 
}

/**
 * 2. PostPage Component (Server Component)
 * Fetches the post content based on the slug.
 */
export default async function PostPage({ params }: PostPageProps) {
  const { slug } = params;
  let postData: PostData;

  try {
    // Fetch the parsed markdown content and metadata using the slug
    postData = await getMarkdownData(slug);
  } catch (error) {
    // If the file is not found (e.g., bad slug), return a 404
    notFound();
  }

  // Render the post using the fetched data
  return <PostContentRenderer post={postData} />;
}